import Navbar from "@/components/navbar/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ConfigProvider } from "@/components/providers/config-provider";
import IsConnectedToOverlay from "@/components/is-connected/is-connected-to-overlay";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider>
          <Navbar />
          <div className="w-full h-fit pl-[215px] py-4 pr-4 flex flex-col gap-4">
            <div className="w-full flex h-fit gap-2">
              <IsConnectedToOverlay />
            </div>
            {children}
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
