import Navbar from "@/components/navbar/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ConfigProvider } from "@/components/providers/config-provider";
import { WebSocketStatusProvider } from "@/components/providers/websocket-status-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider>
          <WebSocketStatusProvider>
            <Navbar />
            <div className="w-full h-fit pl-[215px] py-4 pr-4 flex flex-col gap-4 bg-gray-900 ">
              <div className="w-full flex h-fit gap-2"></div>
              <div className="min-h-screen w-ful p-3 rounded-sm flex flex-col gap-4 text-white">
                {children}
              </div>
            </div>
          </WebSocketStatusProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
