import Navbar from "@/components/navbar/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ConfigProvider } from "@/components/providers/config-provider";
import { WebSocketStatusProvider } from "@/components/providers/websocket-status-provider";
import Header from "@/components/header";
import { CurrentPageProvider } from "@/components/providers/current-page-provider";
import TitleBar from "@/components/title-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} no-scrollbar`}>
        <ConfigProvider>
          <CurrentPageProvider>
            <WebSocketStatusProvider>
              <>
                <TitleBar />
                <div className=" bg-gray-700 h-screen w-screen pt-[26px] pl-8">
                  <div className="w-full flex h-full overflow-hidden rounded-l-lg">
                    <Navbar />
                    <div className="w-full h-full flex flex-col overflow-hidden">
                      <Header />
                      <div className="h-full bg-gray-900  overflow-y-auto w-full p-3 rounded-sm flex flex-col gap-4 text-white">
                        {children}
                      </div>
                    </div>
                  </div>
                </div>
              </>
            </WebSocketStatusProvider>
          </CurrentPageProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
