name: Bug Label Action

permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: write
  
on:
  issues:
    types: [labeled, unlabeled]

jobs:
  update-bug-prefix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Update Issue Title
      run: python workflows/update_issue_title.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
