name: Bug Label Action

permissions:
  contents: read
  issues: write


on:
  issues:
    types: [labeled, unlabeled]

jobs:
  update-bug-prefix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: pip install requests

    - name: Update Issue Title
      run: python .github/workflows/update_issue_title.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        REPOSITORY: ${{ github.repository }}
        ISSUE_LABEL: ${{ github.event.label.name }}
        EVENT_ACTION: ${{ github.event.action }}
