name: Labeling new issue
on:
  issues:
      types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.3.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
