name: Update Issue Titles

on:
  workflow_dispatch:  # Allows manual triggering of the action
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update-issue-titles:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: pip install requests

    - name: Update Issue Titles
      run: python .github/workflows/utils.py --function update_issue_titles
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ github.repository }}
